apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 4moa/moa-be:v7.7.7
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
