apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::315521237353:role/eksctl-moa-cluster-addon-iamserviceaccount-de-Role1-yJ2PLszAAq3c
