apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/100-hours-a-week/4-bull4zo-eks.git'
    targetRevision: main
    path: backend
    repoURL: 'https://github.com/100-hours-a-week/4-bull4zo-eks.git'
    targetRevision: main
    path: redis
  destination:
    server: https://kubernetes.default.svc 
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true